CREATE TABLE characters (
    id INT PRIMARY KEY,
    image VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    class VARCHAR NOT NULL,
    level INT NOT NULL DEFAULT 1,
    background VARCHAR NOT NULL,
    race VARCHAR NOT NULL,
    alignment VARCHAR NOT NULL,
    experience_points INT NOT NULL DEFAULT 0,
    strength INT NOT NULL,
    dexterity INT NOT NULL,
    constitution INT NOT NULL,
    intelligence INT NOT NULL,
    wisdom INT NOT NULL,
    charisma INT NOT NULL,
    proficiency_bonus INT NOT NULL,
    has_inspiration BOOLEAN NOT NULL DEFAULT 'f',
    personality_traits TEXT NOT NULL,
    ideals TEXT NOT NULL,
    bonds TEXT NOT NULL,
    flaws TEXT NOT NULL,
    features_and_traits TEXT NOT NULL,
    other_proficiencies_and_languages TEXT NOT NULL,
    armor_class INT NOT NULL,
    speed INT NOT NULL,
    hit_points INT NOT NULL,
    current_hit_points INT NOT NULL,
    temporary_hit_points INT NOT NULL DEFAULT 0,
    hit_dice INT NOT NULL,
    used_hit_dice INT NOT NULL,
    saves INT NOT NULL DEFAULT 0,
    failures INT NOT NULL DEFAULT 0,
    equipment TEXT NOT NULL,
    copper INT NOT NULL DEFAULT 0,
    silver INT NOT NULL DEFAULT 0,
    electrum INT NOT NULL DEFAULT 0,
    platinum INT NOT NULL DEFAULT 0,
    gold INT NOT NULL DEFAULT 0
);
