CREATE TABLE characters (
    id INT PRIMARY KEY,
    image VARCHAR,
    name VARCHAR NOT NULL,
    class VARCHAR NOT NULL,
    level INT NOT NULL DEFAULT 1,
    background VARCHAR,
    race VARCHAR NOT NULL,
    alignment VARCHAR NOT NULL,
    experience_points INT NOT NULL DEFAULT 0,
    strength INT NOT NULL,
    dexterity INT NOT NULL,
    constitution INT NOT NULL,
    intelligence INT NOT NULL,
    wisdom INT NOT NULL,
    charisma INT NOT NULL,
    proficiency_bonus INT NOT NULL,
    has_inspiration BOOLEAN NOT NULL DEFAULT 'f',
    personality_traits TEXT,
    ideals TEXT,
    bonds TEXT,
    flaws TEXT,
    features_and_traits TEXT,
    other_proficiencies_and_languages TEXT,
    armor_class INT NOT NULL,
    speed INT NOT NULL,
    hit_points INT NOT NULL,
    current_hit_points INT NOT NULL DEFAULT 0,
    temporary_hit_points INT NOT NULL DEFAULT 0,
    hit_dice INT NOT NULL DEFAULT 0,
    used_hit_dice INT NOT NULL DEFAULT 0,
    saves INT NOT NULL DEFAULT 0,
    failures INT NOT NULL DEFAULT 0,
    equipment TEXT,
    copper INT NOT NULL DEFAULT 0,
    silver INT NOT NULL DEFAULT 0,
    electrum INT NOT NULL DEFAULT 0,
    platinum INT NOT NULL DEFAULT 0,
    gold INT NOT NULL DEFAULT 0
);
