[package]
name = "dicebag-server"
version = "0.1.0"
authors = ["Lane Sawyer <github@lanesaywer.dev>"]
edition = "2018"

[dependencies]
# diesel = { version = "1.4.6", features = ["postgres"] }
dotenv = "0.15.0"
juniper = "0.15.6"
juniper_rocket = "0.7.1"
rocket = "0.4.9"
