version: '3'

services:
    server:
        build: .
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - 8000:8000
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - 5432:5432
