version: '3'

volumes:
    postgres_data: {}

services:
    server:
        build: .
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - 8000:8000
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
