version: '3.9'

volumes:
    postgres_data: {}

services:
    server:
        build: .
        environment:
            - ROCKET_SECRET_KEY=${ROCKET_SECRET_KEY}
            - ROCKET_DATABASES={postgres={url=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}}}
        depends_on:
            - db
        ports:
            - 8000:8000
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
