[package]
name = "dicebag"
version = "0.1.0"
authors = ["Lane Sawyer <github@lanesawyer.dev>"]
edition = "2018"

[profile.release]
# Increases execution speed at the cost of compile time
lto = true

[dependencies]
anyhow = "1.0.43"
getrandom = { version = "0.2.3", features = ["js"] }
graphql_client = "0.10.0"
rand = "0.8.4"
serde = "1.0.130"
serde_json = "1.0.67"
wasm-bindgen = "0.2.77"
yew = "0.18.0"
yew-router = "0.15.0"
